# Generated by Django 2.2.4 on 2020-10-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Defaulting', 'Defaulting'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
