from django.urls import path
from .views import (
    UserIDView,
    ProfileDetailView,
    # ProfileCreateView,
    ProfileUpdateView, 
    ProductListView,
    ProductCreateView,
    ProductCategoryListView,
    ProductCategoryCreateView,
    ProductSubCategoryListView,
    ProductSubCategoryCreateView,
    CardPaymentView,
    TenureListView,
    LoanView,
    ProfileImageUpdateView,
    ProfileImageDetailView,
    UserLoanListView,
    CardView,
    AllLoanListView,
    AllLoanDetailView,
    LoanUpdateView,
    UserLoanDetailView,
    ChangePasswordView,
)
from rest_framework import routers
from django.conf.urls import include


urlpatterns = [
    path('user-id/', UserIDView.as_view(), name='user-id'),
    path('tenure/', TenureListView.as_view(), name='tenure'),
    path('loan/', LoanView.as_view(), name='loan'),
    path('user-loans/', UserLoanListView.as_view(), name='user-loans'),
    path('user-loans/<int:pk>/', UserLoanDetailView.as_view(), name='user-loans-detail'),
    path('all-loans/', AllLoanListView.as_view(), name='all-loans'),
    path('all-loans/<int:pk>/', AllLoanDetailView.as_view(), name='loans-detail'),
    path('loan/<pk>/update/', LoanUpdateView.as_view(), name='loan-update'),
    path('card-payment/', CardPaymentView.as_view(), name='card-payment'),
    path('card/', CardView.as_view(), name='card-detail'),
    path('profile/<pk>/', ProfileDetailView.as_view(), name='profile-detail'),
    path('image/<pk>/', ProfileImageDetailView.as_view(), name='image-detail'),
    path('change-password/<pk>/update/', ChangePasswordView.as_view(), name='password-change'),
    path('profile/<pk>/update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('image/<pk>/update/', ProfileImageUpdateView.as_view(), name='image-update'),
    path('subscription-products/', ProductListView.as_view(), name='subscription-products'),
    path('subscription-products/create/', ProductCreateView.as_view(), name='subscription-products-create'),
    path('subscription-products-category/', ProductCategoryListView.as_view(), name='subscription-products-category'),
    path('subscription-products-category/create/', ProductCategoryCreateView.as_view(), name='subscription-products-category-create'),
    path('subscription-products-sub-category/', ProductSubCategoryListView.as_view(), name='subscription-products-sub-category'),
    path('subscription-products-sub-category/create/', ProductSubCategoryCreateView.as_view(), name='subscription-products-sub-category-create'),
]
